/*
Baseten management API

REST API for management of Baseten resources

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  AutoscalingSettingApi,
  DeploymentApi,
  ModelApi,
  SecretApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { BasetenCustom } from "./client-custom";

export class Baseten extends BasetenCustom {
  readonly autoscalingSetting: AutoscalingSettingApi;
  readonly deployment: DeploymentApi;
  readonly model: ModelApi;
  readonly secret: SecretApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.autoscalingSetting = new AutoscalingSettingApi(configuration);
    this.deployment = new DeploymentApi(configuration);
    this.model = new ModelApi(configuration);
    this.secret = new SecretApi(configuration);
  }

}
