/*
Baseten management API

REST API for management of Baseten resources

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DeploymentV1 } from './deployment-v1';

/**
 * A list of deployments of a model.
 * @export
 * @interface DeploymentsV1
 */
export interface DeploymentsV1 {
    /**
     * A list of deployments of a model
     * @type {Array<DeploymentV1>}
     * @memberof DeploymentsV1
     */
    'deployments': Array<DeploymentV1>;
}

