/*
Baseten management API

REST API for management of Baseten resources

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AutoscalingSettingsV1 } from './autoscaling-settings-v1';
import { DeploymentStatusV1 } from './deployment-status-v1';

/**
 * A deployment of a model.
 * @export
 * @interface DeploymentV1
 */
export interface DeploymentV1 {
    /**
     * Unique identifier of the deployment
     * @type {string}
     * @memberof DeploymentV1
     */
    'id': string;
    /**
     * Time the deployment was created in ISO 8601 format
     * @type {string}
     * @memberof DeploymentV1
     */
    'created_at': string;
    /**
     * Name of the deployment
     * @type {string}
     * @memberof DeploymentV1
     */
    'name': string;
    /**
     * Unique identifier of the model
     * @type {string}
     * @memberof DeploymentV1
     */
    'model_id': string;
    /**
     * Whether the deployment is the production deployment of the model
     * @type {boolean}
     * @memberof DeploymentV1
     */
    'is_production': boolean;
    /**
     * Whether the deployment is the development deployment of the model
     * @type {boolean}
     * @memberof DeploymentV1
     */
    'is_development': boolean;
    /**
     * Status of the deployment
     * @type {DeploymentStatusV1}
     * @memberof DeploymentV1
     */
    'status': DeploymentStatusV1;
    /**
     * Number of active replicas
     * @type {number}
     * @memberof DeploymentV1
     */
    'active_replica_count': number;
    /**
     * Autoscaling settings for the deployment
     * @type {AutoscalingSettingsV1}
     * @memberof DeploymentV1
     */
    'autoscaling_settings': AutoscalingSettingsV1;
}

