/*
Baseten management API

REST API for management of Baseten resources

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ModelV1 } from './model-v1';

/**
 * A list of models.
 * @export
 * @interface ModelsV1
 */
export interface ModelsV1 {
    /**
     * 
     * @type {Array<ModelV1>}
     * @memberof ModelsV1
     */
    'models': Array<ModelV1>;
}

