/*
Baseten management API

REST API for management of Baseten resources

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A request to promote a deployment to production.
 * @export
 * @interface PromoteRequestV1
 */
export interface PromoteRequestV1 {
    /**
     * Whether to scale down the previous production deployment after promoting
     * @type {boolean}
     * @memberof PromoteRequestV1
     */
    'scale_down_previous_production'?: boolean;
}

