/*
Baseten management API

REST API for management of Baseten resources

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SecretV1 } from './secret-v1';

/**
 * A list of Baseten secrets.
 * @export
 * @interface SecretsV1
 */
export interface SecretsV1 {
    /**
     * 
     * @type {Array<SecretV1>}
     * @memberof SecretsV1
     */
    'secrets': Array<SecretV1>;
}

