/*
Baseten management API

REST API for management of Baseten resources

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The status of a request to update autoscaling settings.
 * @export
 * @enum {string}
 */
export type UpdateAutoscalingSettingsStatusV1 = 'ACCEPTED' | 'QUEUED' | 'UNCHANGED'

