/*
Baseten management API

REST API for management of Baseten resources

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A request to update autoscaling settings for a deployment. All fields are optional, and we only update ones passed in.
 * @export
 * @interface UpdateAutoscalingSettingsV1
 */
export interface UpdateAutoscalingSettingsV1 {
    /**
     * Minimum number of replicas
     * @type {number}
     * @memberof UpdateAutoscalingSettingsV1
     */
    'min_replica'?: number;
    /**
     * Maximum number of replicas
     * @type {number}
     * @memberof UpdateAutoscalingSettingsV1
     */
    'max_replica'?: number;
    /**
     * Timeframe of traffic considered for autoscaling decisions
     * @type {number}
     * @memberof UpdateAutoscalingSettingsV1
     */
    'autoscaling_window'?: number;
    /**
     * Waiting period before scaling down any active replica
     * @type {number}
     * @memberof UpdateAutoscalingSettingsV1
     */
    'scale_down_delay'?: number;
    /**
     * Number of requests per replica before scaling up
     * @type {number}
     * @memberof UpdateAutoscalingSettingsV1
     */
    'concurrency_target'?: number;
}

