/*
Baseten management API

REST API for management of Baseten resources

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A request to create or update a Baseten secret by name.
 * @export
 * @interface UpsertSecretRequestV1
 */
export interface UpsertSecretRequestV1 {
    /**
     * Name of the new or existing secret
     * @type {string}
     * @memberof UpsertSecretRequestV1
     */
    'name': string;
    /**
     * Value of the secret
     * @type {string}
     * @memberof UpsertSecretRequestV1
     */
    'value': string;
}

